export const stanovi = [{
  name: '2.1',
  stan: '1',
  brojSoba: 3,
  stanje: 'slobodan',
  kvadrature: [
    { name: 'ULAZ', size: 7.50 },
    { name: 'OSTAVA', size: null },
    { name: 'HODNIK', size: null },
    { name: 'WC', size: 2.03 },
    { name: 'KUHINJA', size: 5.70 },
    { name: 'KUHINJA I TRPEZARIJA', size: null },
    { name: 'DN. BORAVAK I TRPEZARIJA', size: 23.81 },
    { name: 'DN. BORAVAK', size: null },
    { name: 'DEGAEMAN', size: 4.91 },
    { name: 'KUPATILO', size: 6.58 },
    { name: 'KUPATILO', size: null },
    { name: 'SOBA 1', size: 9.62 },
    { name: 'SOBA 2', size: 11.03 },
    { name: 'SOBA 3', size: null },
    { name: 'LOĐA', size: 4.80 },
    { name: 'TERASA', size: null },
    { name: 'SAMO STAN', size: 71.18 },
    { name: 'UKUPNE POVRSINE', size: 75.98 }
  ]
}, {
  name: '2.2',
  stan: '2',
  brojSoba: 3,
  stanje: 'prodat',
  kvadrature: [
    { name: 'ULAZ', size: 4.41 },
    { name: 'OSTAVA', size: null },
    { name: 'HODNIK', size: 8.06 },
    { name: 'WC', size: 1.87 },
    { name: 'KUHINJA', size: 6.76 },
    { name: 'KUHINJA I TRPEZARIJA', size: null },
    { name: 'DN. BORAVAK I TRPEZARIJA', size: 18.09 },
    { name: 'DN. BORAVAK', size: null },
    { name: 'DEGAEMAN', size: null },
    { name: 'KUPATILO', size: 5.27 },
    { name: 'KUPATILO', size: null },
    { name: 'SOBA 1', size: 10.33 },
    { name: 'SOBA 2', size: 10.53 },
    { name: 'SOBA 3', size: null },
    { name: 'LOĐA', size: null },
    { name: 'TERASA', size: 35.69 },
    { name: 'SAMO STAN', size: 65.32 },
    { name: 'UKUPNE POVRSINE', size: 101.01 }
  ]
}, {
  name: '2.3',
  stan: '3',
  brojSoba: 3,
  stanje: 'slobodan',
  kvadrature: [
    { name: 'ULAZ', size: 4.70 },
    { name: 'OSTAVA', size: null },
    { name: 'HODNIK', size: 1.96 },
    { name: 'WC', size: 2.03 },
    { name: 'KUHINJA', size: 6.46 },
    { name: 'KUHINJA I TRPEZARUA', size: null },
    { name: 'DN. BORAVAK I TRPEZARUA', size: 18.52 },
    { name: 'DN. BORAVAK', size: null },
    { name: 'DEGAZMAN', size: 3.71 },
    { name: 'KUPATILO', size: 6.30 },
    { name: 'KUPATILO', size: null },
    { name: 'SOBA 1', size: 9.51 },
    { name: 'SOBA 2', size: 9.05 },
    { name: 'SOBA 3', size: null },
    { name: 'LOĐA', size: null },
    { name: 'TERASA', size: 21.84 },
    { name: 'SAMO STAN', size: 62.24 },
    { name: 'UKUPNE POVRSINE', size: 84.08 }
  ]  
}, {
  name: '2.4',
  stan: '4',
  brojSoba: 2,
  stanje: 'slobodan',
  kvadrature: [
    { name: 'ULAZ', size: 3.00 },
    { name: 'OSTAVA', size: null },
    { name: 'HODNIK', size: 2.99 },
    { name: 'WC', size: null },
    { name: 'KUHINJA', size: 5.94 },
    { name: 'KUHINJA I TRPEZARIJA', size: null },
    { name: 'DN. BORAVAK I TRPEZARIJA', size: 23.79 },
    { name: 'DN. BORAVAK', size: null },
    { name: 'DEGAZMAN', size: null },
    { name: 'KUPATILO', size: 5.98 },
    { name: 'KUPATILO', size: null },
    { name: 'SOBA 1', size: 13.13 },
    { name: 'SOBA 2', size: null },
    { name: 'SOBA 3', size: null },
    { name: 'LOĐA', size: null },
    { name: 'TERASA', size: null },
    { name: 'SAMO STAN', size: 54.83 },
    { name: 'UKUPNE POVRSINE', size: 54.83 }
  ]  
}]
