export const stanovi = [{
  name: '3.1',
  stan: '1',
  brojSoba: 3,
  stanje: 'prodat',
  img: 'Stan 1.svg',
  kvadrature: [
    { name: 'ULAZ', size: 7.50 },
    { name: 'OSTAVA', size: null },
    { name: 'HODNIK', size: null },
    { name: 'WC', size: 2.03 },
    { name: 'KUHINJA', size: 5.70 },
    { name: 'KUHINJA I TRPEZARIJA', size: null },
    { name: 'DN. BORAVAK I TRPEZARIJA', size: 23.81 },
    { name: 'DN. BORAVAK', size: null },
    { name: 'DEGAZMAN', size: 4.91 },
    { name: 'KUPATILO', size: 6.58 },
    { name: 'KUPATILO', size: null },
    { name: 'SOBA 1', size: 9.62 },
    { name: 'SOBA 2', size: 11.03 },
    { name: 'SOBA 3', size: null },
    { name: 'LOĐA', size: 4.80 },
    { name: 'TERASA', size: null },
    { name: 'SAMO STAN', size: 71.18 },
    { name: 'UKUPNE POVRSINE', size: 75.98 }
  ]
}, {
  name: '3.2',
  stan: '2',
  brojSoba: 2,
  img: 'Stan 2.svg',
  stanje: 'slobodan',
  kvadrature: [
    { name: 'ULAZ', size: 3.27 },
    { name: 'OSTAVA', size: null },
    { name: 'HODNIK', size: 7.70 },
    { name: 'WC', size: 1.69 },
    { name: 'KUHINJA', size: 5.49 },
    { name: 'KUHINJA I TRPEZARIJA', size: null },
    { name: 'DN. BORAVAK I TRPEZARIJA', size: 17.39 },
    { name: 'DN. BORAVAK', size: null },
    { name: 'DEGAZMAN', size: null },
    { name: 'KUPATILO', size: 5.93 },
    { name: 'KUPATILO', size: null },
    { name: 'SOBA 1', size: 10.24 },
    { name: 'SOBA 2', size: null },
    { name: 'SOBA 3', size: null },
    { name: 'LOĐA', size: null },
    { name: 'TERASA', size: 17.47 },
    { name: 'SAMO STAN', size: 51.71 },
    { name: 'UKUPNE POVRSINE', size: 69.18 }
  ]   
}, {
  name: '3.3',
  stan: '3',
  brojSoba: 1,
  img: 'Stan 3.png',
  stanje: 'slobodan',
  kvadrature: [
    { name: 'ULAZ', size: 4.70 },
    { name: 'OSTAVA', size: 2.03 },
    { name: 'HODNIK', size: 1.96 },
    { name: 'WC', size: null },
    { name: 'KUHINJA', size: 6.46 },
    { name: 'KUHINJA I TRPEZARIJA', size: null },
    { name: 'DN. BORAVAK I TRPEZARUJA', size: 18.52 },
    { name: 'DN. BORAVAK', size: null },
    { name: 'DEGAZMAN', size: null },
    { name: 'KUPATILO', size: 6.30 },
    { name: 'KUPATILO', size: null },
    { name: 'SOBA 1', size: null },
    { name: 'SOBA 2', size: null },
    { name: 'SOBA 3', size: null },
    { name: 'LODA', size: null },
    { name: 'TERASA', size: 19.29 },
    { name: 'SAMO STAN', size: 39.97 },
    { name: 'UKUPNE POVRSINE', size: 59.26 }
  ]
}, {
  name: '3.4',
  stan: '4',
  brojSoba: 2,
  stanje: 'rezervisan',
  img: 'Stan 4.png',
  kvadrature: [
    { name: 'ULAZ', size: 3.00 },
    { name: 'OSTAVA', size: null },
    { name: 'HODNIK', size: 2.99 },
    { name: 'WC', size: null },
    { name: 'KUHINJA', size: 5.94 },
    { name: 'KUHINJA I TRPEZARIJA', size: null },
    { name: 'DN. BORAVAK I TRPEZARUJA', size: 23.79 },
    { name: 'DN. BORAVAK', size: null },
    { name: 'DEGAZMAN', size: null },
    { name: 'KUPATILO', size: 5.98 },
    { name: 'KUPATILO', size: null },
    { name: 'SOBA 1', size: 13.13 },
    { name: 'SOBA 2', size: null },
    { name: 'SOBA 3', size: null },
    { name: 'LODA', size: null },
    { name: 'TERASA', size: null },
    { name: 'SAMO STAN', size: 54.83 },
    { name: 'UKUPNE POVRSINE', size: 54.83 }
  ]
}]
