export const stanovi = [{
  name: 'P.1',
  stan: '1',
  brojSoba: 3,
  stanje: 'prodat',
  kvadrature: [
    { name: 'ULAZ', size: 7.50 },
    { name: 'OSTAVA', size: null },
    { name: 'HODNIK', size: null },
    { name: 'WC', size: 2.03 },
    { name: 'KUHINJA', size: 5.7 },
    { name: 'KUHINJA I TRPEZARIJA', size: null },
    { name: 'DN. BORAVAK I TRPEZARIJA', size: 23.81 },
    { name: 'DN. BORAVAK', size: null },
    { name: 'DEGAZMAN', size: 4.91 },
    { name: 'KUPATILO', size: 6.58 },
    { name: 'KUPATILO', size: null },
    { name: 'SOBA 1', size: 9.62 },
    { name: 'SOBA 2', size: 11.03 },
    { name: 'SOBA 3', size: null },
    { name: 'LOĐA', size: 4.80 },
    { name: 'TERASA', size: null },
    { name: 'SAMO STAN', size: 71.18 },
    { name: 'UKUPNE POVRSINE', size: 75.98 }
  ]
}, {
  name: 'P.2',
  stan: '2',
  brojSoba: 4,
  stanje: 'prodat',
  kvadrature: [
    { name: 'ULAZ', size: 3.61 },
    { name: 'OSTAVA', size: 2.88 },
    { name: 'HODNIK', size: 9.6 },
    { name: 'WC', size: null },
    { name: 'KUHINJA', size: 5.66 },
    { name: 'KUHINJA I TRPEZARIJA', size: null },
    { name: 'DN. BORAVAK I TRPEZARIJA', size: 17.37 },
    { name: 'DN. BORAVAK', size: null },
    { name: 'DEGAZMAN', size: 6.03 },
    { name: 'KUPATILO', size: 5.18 },
    { name: 'KUPATILO', size: 5.93 },
    { name: 'SOBA 1', size: 12.89 },
    { name: 'SOBA 2', size: 10.55 },
    { name: 'SOBA 3', size: 9.88 },
    { name: 'LOĐA', size: 10.46 },
    { name: 'TERASA', size: null },
    { name: 'SAMO STAN', size: 89.58 },
    { name: 'UKUPNE POVRSINE', size: 100.04 }
  ]
}, {
  name: 'P.3',
  stan: '3',
  brojSoba: 3,
  stanje: 'prodat',
  kvadrature: [
    { name: 'ULAZ', size: 3.28 },
    { name: 'OSTAVA', size: null },
    { name: 'HODNIK', size: null },
    { name: 'WC', size: 2.42 },
    { name: 'KUHINJA', size: 6.44 },
    { name: 'KUHINJA I TRPEZARIJA', size: null },
    { name: 'DN. BORAVAK I TRPEZARIJA', size: 26.29 },
    { name: 'DN. BORAVAK', size: null },
    { name: 'DEGAEMAN', size: 5.85 },
    { name: 'KUPATILO', size: 5.20 },
    { name: 'KUPATILO', size: null },
    { name: 'SOBA 1', size: 10.66 },
    { name: 'SOBA 2', size: 9.30 },
    { name: 'SOBA 3', size: null },
    { name: 'LOĐA', size: 4.53 },
    { name: 'TERASA', size: null },
    { name: 'SAMO STAN', size: 69.44 },
    { name: 'UKUPNE POVRSINE', size: 73.97 }
  ]
}, {
  name: 'P.4',
  stan: '4',
  brojSoba: 2,
  stanje: 'prodat',
  kvadrature: [
    { name: 'ULAZ', size: 3.00 },
    { name: 'OSTAVA', size: null },
    { name: 'HODNIK', size: 2.99 },
    { name: 'WC', size: null },
    { name: 'KUHINJA', size: 5.94 },
    { name: 'KUHINJA I TRPEZARIJA', size: null },
    { name: 'DN. BORAVAK I TRPEZARIJA', size: 23.79 },
    { name: 'DN. BORAVAK', size: null },
    { name: 'DEGAEMAN', size: null },
    { name: 'KUPATILO', size: 5.98 },
    { name: 'KUPATILO', size: null },
    { name: 'SOBA 1', size: 13.13 },
    { name: 'SOBA 2', size: null },
    { name: 'SOBA 3', size: null },
    { name: 'LOĐA', size: null },
    { name: 'TERASA', size: null },
    { name: 'SAMO STAN', size: 54.83 },
    { name: 'UKUPNE POVRSINE', size: 54.83 }
  ]
}]
